[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.25.1"
ci = "github"
installers = []
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]

[dist.dependencies.apt]
libudev-dev = '*'
